// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission_4.Models;

namespace Mission_4.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission_4.Models.FormResponse", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            Category = "Comedy",
                            Director = "Jared Hess",
                            Edit = false,
                            Rating = "PG",
                            Title = "Nacho Libre",
                            Year = 2006u
                        },
                        new
                        {
                            FormId = 2,
                            Category = "Sci-fi/Adventure",
                            Director = "Christopher Nolan",
                            Edit = false,
                            Rating = "PG-13",
                            Title = "Interstellar",
                            Year = 2014u
                        },
                        new
                        {
                            FormId = 3,
                            Category = "Action/Adventure",
                            Director = "Jon Favreau",
                            Edit = false,
                            Rating = "PG-13",
                            Title = "Iron Man",
                            Year = 2008u
                        },
                        new
                        {
                            FormId = 4,
                            Category = "Musical/Romance",
                            Director = "Bill Condon",
                            Edit = false,
                            Rating = "PG",
                            Title = "Beauty and the Beast",
                            Year = 2017u
                        },
                        new
                        {
                            FormId = 5,
                            Category = "Action/Adventure",
                            Director = "Jon Watts",
                            Edit = false,
                            Rating = "PG-13",
                            Title = "Spider-Man: No Way Home",
                            Year = 2021u
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
